// src/config/worlds.config.js
// 10 CircleQuest Worlds Aligned with Singapore MOE Primary 6 Measurement: Circles (Area)

export const WORLDS = [
  {
    id: 0,
    name: 'Circle Basics Court',
    emoji: '🎯',
    accent: '#FFD54F',
    description: 'Radius, diameter, and pi basics',
    conceptFocus: 'basics',
    boss: { name: 'The Definition Keeper', emoji: '📐', reward: 'Definition Badge 📐' },
  },
  {
    id: 1,
    name: 'Garden Grove',
    emoji: '🌻',
    accent: '#66BB6A',
    description: 'Area from a given radius',
    conceptFocus: 'area_from_radius',
    boss: { name: 'Garden Boss', emoji: '🌻', reward: 'Garden Badge 🌻' },
  },
  {
    id: 2,
    name: 'Pizza Parlour',
    emoji: '🍕',
    accent: '#FF8A65',
    description: 'Area from a given diameter',
    conceptFocus: 'area_from_diameter',
    boss: { name: 'Pizza Master', emoji: '🍕', reward: 'Pizza Badge 🍕' },
  },
  {
    id: 3,
    name: 'Clock Tower Plaza',
    emoji: '🕐',
    accent: '#4FC3F7',
    description: 'Area of a semicircle',
    conceptFocus: 'semicircle',
    boss: { name: 'Clock Keeper', emoji: '🕐', reward: 'Clock Badge 🕐' },
  },
  {
    id: 4,
    name: 'Wheel Works Garage',
    emoji: '⚙️',
    accent: '#B0BEC5',
    description: 'Area of a quarter circle',
    conceptFocus: 'quarter_circle',
    boss: { name: 'Wheel Boss', emoji: '⚙️', reward: 'Wheel Badge ⚙️' },
  },
  {
    id: 5,
    name: 'Mystery Radius Lab',
    emoji: '🔍',
    accent: '#BA68C8',
    description: 'Work backwards from area',
    conceptFocus: 'reverse_radius',
    boss: { name: 'Mystery Boss', emoji: '🔍', reward: 'Mystery Badge 🔍' },
  },
  {
    id: 6,
    name: 'Coin & Compass Collectors',
    emoji: '🪙',
    accent: '#FFCA28',
    description: 'Compare and order circle areas',
    conceptFocus: 'compare',
    boss: { name: 'Compass Boss', emoji: '🧭', reward: 'Compass Badge 🧭' },
  },
  {
    id: 7,
    name: 'Running Track Stadium',
    emoji: '🏟️',
    accent: '#EF5350',
    description: 'Composite figures: track shape',
    conceptFocus: 'composite_track',
    boss: { name: 'Track Boss', emoji: '🏟️', reward: 'Track Badge 🏟️' },
  },
  {
    id: 8,
    name: 'Pattern & Design Studio',
    emoji: '🎨',
    accent: '#26C6DA',
    description: 'Shaded / remaining area',
    conceptFocus: 'shaded_region',
    boss: { name: 'Design Boss', emoji: '🎨', reward: 'Design Badge 🎨' },
  },
  {
    id: 9,
    name: 'Grand Circular Showcase',
    emoji: '🏆',
    accent: '#FFC107',
    description: 'Mixed review & word problems',
    conceptFocus: 'mixed_review',
    boss: { name: 'The Circle Champion', emoji: '👑', reward: 'Circle Master Badge 👑' },
  },
];

export const PLAY_MODES = [
  {
    id: 'guided',
    name: 'Guided Practice',
    icon: '🧭',
    desc: '5 questions with hints, no pressure',
    questionCount: 5,
    hints: true,
    timed: false,
    lives: false,
  },
  {
    id: 'independent',
    name: 'Independent Practice',
    icon: '✍️',
    desc: '10 questions, no hints, full XP',
    questionCount: 10,
    hints: false,
    timed: false,
    lives: false,
  },
  {
    id: 'timed',
    name: 'Timed Challenge',
    icon: '⏱️',
    desc: '8 questions in 60 seconds, bonus XP',
    questionCount: 8,
    hints: false,
    timed: true,
    timeLimit: 60,
    lives: false,
  },
  {
    id: 'boss',
    name: 'Boss Battle',
    icon: '👑',
    desc: '5 questions, 3 lives — defeat the boss!',
    questionCount: 5,
    hints: false,
    timed: false,
    lives: true,
  },
];

export const XP_REWARDS = {
  CORRECT: 10,
  STREAK_BONUS: 15,
  STATION_COMPLETE: 20,
  WORLD_COMPLETE: 50,
  BOSS_WIN: 100,
};
